-- 
-- TABLE: F_HGCG_ARTICULO_2 
--


CREATE TABLE F_HGCG_ARTICULO_2(
    ARTICULO_ID    NUMERIC(38, 0)   NOT NULL,
    TITULO         VARCHAR2(40)     NOT NULL,
    RESUMEN        VARCHAR2(40)     NOT NULL,
    TEXTO          VARCHAR2(40)     NOT NULL,
    CONSTRAINT F_HGCG_ARTICULO_ID_2_PK PRIMARY KEY (ARTICULO_ID)
);

-- 
-- TABLE: F_HGCG_REVISTA_1 
--

CREATE TABLE F_HGCG_REVISTA_1(
    REVISTA_ID              NUMERIC(38, 0)   NOT NULL,
    FOLIO                   VARCHAR2(40)     NOT NULL,
    TITULO                  VARCHAR2(40)     NOT NULL,
    FECHA_PUBLICACION       DATE             NOT NULL,
    REVISTA_ADICIONAL_ID    NUMERIC(38, 0)    NOT NULL,
    CONSTRAINT F_HGCG_REVISTA_ID_1_PK PRIMARY KEY (REVISTA_ID)
);

-- 
-- TABLE: F_HGCG_ARTICULO_REVISTA_1 
--

CREATE TABLE F_HGCG_ARTICULO_REVISTA_1(
    ARTICULO_REVISTA_ID    NUMERIC(38, 0)    NOT NULL,
    ARTICULO_ID            NUMERIC(38, 0),
    REVISTA_ID             NUMERIC(38, 0),
    FECHA_APROBACION       DATE             NOT NULL,
    CALIFICACION           NUMERIC(38, 0)    NOT NULL,
    --Primary Key
    CONSTRAINT F_HGCG_ARTICULO_REVISTA_ID_1_PK PRIMARY KEY (ARTICULO_REVISTA_ID),
    --LLave foranea de  articulo_Revista a articulo_2
    CONSTRAINT ART_ART_REV_ID_FK FOREIGN KEY (ARTICULO_ID)
    REFERENCES F_HGCG_ARTICULO_2(ARTICULO_ID),
    --LLave foranea de  articulo_Revista a revista_1
    CONSTRAINT REV_ART_REV_ID_FK FOREIGN KEY (REVISTA_ID)
    REFERENCES F_HGCG_REVISTA_1(REVISTA_ID)
);


-- 
-- TABLE: F_HGCG_SUSCRIPTOR_1 
--

CREATE TABLE F_HGCG_SUSCRIPTOR_1(
    SUSCRIPTOR_ID    NUMERIC(38, 0)   NOT NULL,
    NUM_TARJETA      VARCHAR2(16)     NOT NULL,
    CONSTRAINT F_HGCG_SUSCRIPTOR_ID_1_PK PRIMARY KEY (SUSCRIPTOR_ID)
);

-- 
-- TABLE: F_HGCG_PAGO_SUSCRIPTOR_1 
--

CREATE TABLE F_HGCG_PAGO_SUSCRIPTOR_1(
    SUSCRIPTOR_ID    NUMERIC(38, 0)   NOT NULL,
    NUM_PAGO         NUMERIC(38, 0)   NOT NULL,
    FECHA_PAGO       DATE             NOT NULL,
    IMPORTE          NUMERIC(38, 2)   NOT NULL,
    RECIBO_PAGO      BLOB,
    CONSTRAINT SUSC_PAGO_SUSC_ID1_FK FOREIGN KEY(SUSCRIPTOR_ID)
    REFERENCES F_HGCG_SUSCRIPTOR_1(SUSCRIPTOR_ID)
);

-- 
-- TABLE: F_HGCG_PAIS_1 
--

CREATE TABLE F_HGCG_PAIS_1(
    PAIS_ID             NUMERIC(38, 0)   NOT NULL,
    CLAVE               VARCHAR2(40)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    REGION_ECONOMICA    CHAR(40)         NOT NULL,
    CONSTRAINT F_HGCG_PAIS_ID_1_PK PRIMARY KEY (PAIS_ID)
);

-- 
-- TABLE: F_HGCG_SUSCRIPTOR_2 
--

CREATE TABLE F_HGCG_SUSCRIPTOR_2(
    SUSCRIPTOR_ID        NUMERIC(38, 0)   NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    AP_PATERNO           VARCHAR2(40)     NOT NULL,
    AP_MATERNO           VARCHAR2(40)     NOT NULL,
    FECHA_PUBLICACION    DATE             NOT NULL,
    PAIS_ID              NUMERIC(38, 0)    NOT NULL,
    CONSTRAINT F_HGCG_SUSCRIPTOR_ID_2_PK PRIMARY KEY (SUSCRIPTOR_ID),
    CONSTRAINT PAIS_SUSC2_ID_FK FOREIGN KEY(PAIS_ID)
    REFERENCES F_HGCG_PAIS_1(PAIS_ID)
);
-- 
-- TABLE: F_HGCG_SUSCRIPTOR_3 
--

CREATE TABLE F_HGCG_SUSCRIPTOR_3(
    SUSCRIPTOR_ID        NUMERIC(38, 0)   NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    AP_PATERNO           VARCHAR2(40)     NOT NULL,
    AP_MATERNO           VARCHAR2(40)     NOT NULL,
    FECHA_PUBLICACION    DATE             NOT NULL,
    PAIS_ID              NUMERIC(38, 0)    NOT NULL,
    CONSTRAINT F_HGCG_SUSCRIPTOR_ID_3_PK PRIMARY KEY (SUSCRIPTOR_ID)
);