-- 
-- TABLE: F_HGCG_PAGO_SUCRUPTOR_2 
--

CREATE TABLE F_HGCG_PAGO_SUSCRIPTOR_2(
    NUM_PAGO       NUMBER(38, 0)    NOT NULL,
    SUSCRIPTOR_ID  NUMBER(38, 0)    NOT NULL,
    FECHA_PAGO     DATE             NOT NULL,
    IMPORTE        NUMBER(10, 2)    NOT NULL,
    RECIBO_PAGO    BLOB          NOT NULL,
    CONSTRAINT F_HGCG_PAGO_SUSCRIPTOR_2_PK PRIMARY KEY (SUSCRIPTOR_ID, NUM_PAGO)
);

-- 
-- TABLE: F_HGCG_REVISTA_2 
--

CREATE TABLE F_HGCG_REVISTA_2(
    REVISTA_ID              NUMBER(38, 0)    NOT NULL,
    FOLIO                   VARCHAR2(40)     NOT NULL,
    TITULO                  VARCHAR2(40)     NOT NULL,
    FECHA_PUBLICACION       DATE             NOT NULL,
    REVISTA_ADICIONAL_ID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT F_HGCG_REVISTA_2_PK PRIMARY KEY(REVISTA_ID)
);

-- 
-- TABLE: F_HGCG_ARTICULO_1 

CREATE TABLE F_HGCG_ARTICULO_1(
    ARTICULO_ID    NUMBER(38, 0)    NOT NULL,
    PDF            BLOB             NOT NULL,
    CONSTRAINT F_HGCG_ARTICULO_1_PK PRIMARY KEY(ARTICULO_ID)
);

-- 
-- TABLE: F_HGCG_ARTICULO_REVISTA_2 
--

CREATE TABLE F_HGCG_ARTICULO_REVISTA_2(
    ARTICULO_REVISTA_ID    NUMBER(38, 0)    NOT NULL,
    FECHA_APROBACION       DATE             NOT NULL,
    CALIFICACION           NUMBER(38, 0)    NOT NULL,
    ARTICULO_ID            NUMBER(38, 0)    NOT NULL,
    REVISTA_ID             NUMBER(38, 0)    NOT NULL,
    CONSTRAINT F_HGCG_ARTICULO_REVISTA_2_PK PRIMARY KEY (ARTICULO_REVISTA_ID),
    CONSTRAINT REV_ARTREV2_ID_FK FOREIGN KEY (REVISTA_ID)
    REFERENCES F_HGCG_REVISTA_2(REVISTA_ID),
    CONSTRAINT ART_ARTREV2_IF_FK FOREIGN KEY(REVISTA_ID)
    REFERENCES F_HGCG_ARTICULO_1(ARTICULO_ID)
);

-- 
-- TABLE: F_HGCG_PAIS_2 
--x|
CREATE TABLE F_HGCG_PAIS_2(
    PAIS_ID             NUMBER(38, 0)    NOT NULL,
    CLAVE               VARCHAR2(40)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    REGION_ECONOMICA    VARCHAR2(40)     NOT NULL,
    CONSTRAINT F_HGCG_PAIS_2_PK PRIMARY KEY(PAIS_ID)
);

-- 
-- TABLE: F_HGCG_SUSCRIPTOR_4 
--

CREATE TABLE F_HGCG_SUSCRIPTOR_4(
    SUSCRIPTOR_ID        NUMBER(38, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    AP_PATERNO           VARCHAR2(40)     NOT NULL,
    AP_MATERNO           VARCHAR2(40),
    FECHA_PUBLICACION    DATE             NOT NULL,
    PAIS_ID              NUMBER(38, 0)    NOT NULL,
    CONSTRAINT F_HGCG_SUSCRIPTOR_4_PK PRIMARY KEY(SUSCRIPTOR_ID),
    CONSTRAINT PAIS_SUSC4_ID_FK FOREIGN KEY (PAIS_ID)
    REFERENCES F_HGCG_PAIS_2(PAIS_ID)
);