--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      sitio 2.DM1
-- Author :       Windows User
--
-- Date Created : Tuesday, November 10, 2020 00:22:22
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: F_HGCG_ARTICULO_1 
--

CREATE TABLE F_HGCG_ARTICULO_1(
    ARTICULO_ID    NUMBER(38, 0)    NOT NULL,
    PDF            BLOB             NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (ARTICULO_ID)
)
;



-- 
-- TABLE: F_HGCG_ARTICULO_REVISTA_2 
--

CREATE TABLE F_HGCG_ARTICULO_REVISTA_2(
    ARTICULO_REVISTA_ID    NUMBER(38, 0)    NOT NULL,
    FECHA_APROBACION       DATE             NOT NULL,
    CALIFICACION           NUMBER(5, 2)     NOT NULL,
    ARTICULO_ID            NUMBER(38, 0)    NOT NULL,
    REVISTA_ID             NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (ARTICULO_REVISTA_ID)
)
;



-- 
-- TABLE: F_HGCG_PAGO_SUCRIPTOR_2 
--

CREATE TABLE F_HGCG_PAGO_SUCRIPTOR_2(
    REVISTA_ID     NUMBER(38, 0)    NOT NULL,
    PDF            NUMBER(38, 0)    NOT NULL,
    FECHA_PAGO     DATE             NOT NULL,
    IMPORTE        NUMBER(10, 2)    NOT NULL,
    RECIBO_PAGO    BLOB             NOT NULL,
    CONSTRAINT PK1_1 PRIMARY KEY (REVISTA_ID, PDF)
)
;



-- 
-- TABLE: F_HGCG_PAIS_2 
--

CREATE TABLE F_HGCG_PAIS_2(
    PAIS_ID             NUMBER(38, 0)    NOT NULL,
    CLAVE               VARCHAR2(40)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    REGION_ECONOMICA    VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK5_1 PRIMARY KEY (PAIS_ID)
)
;



-- 
-- TABLE: F_HGCG_REVISTA_2 
--

CREATE TABLE F_HGCG_REVISTA_2(
    REVISTA_ID              NUMBER(38, 0)    NOT NULL,
    FOLIO                   VARCHAR2(38)     NOT NULL,
    TITULO                  VARCHAR2(38)     NOT NULL,
    FECHA_PUBLICACION       DATE             NOT NULL,
    REVISTA_ADICIONAL_ID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (REVISTA_ID)
)
;



-- 
-- TABLE: F_HGCG_SUSCRIPTOR_4 
--

CREATE TABLE F_HGCG_SUSCRIPTOR_4(
    SUSCRIPTOR_ID        NUMBER(40, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    AP_PATERNO           VARCHAR2(40)     NOT NULL,
    AP_MATERNO           VARCHAR2(40),
    FECHA_PUBLICACION    VARCHAR2(40)     NOT NULL,
    PAIS_ID              NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (SUSCRIPTOR_ID)
)
;



-- 
-- TABLE: F_HGCG_ARTICULO_REVISTA_2 
--

ALTER TABLE F_HGCG_ARTICULO_REVISTA_2 ADD CONSTRAINT RefF_HGCG_ARTICULO_18 
    FOREIGN KEY (ARTICULO_ID)
    REFERENCES F_HGCG_ARTICULO_1(ARTICULO_ID)
;

ALTER TABLE F_HGCG_ARTICULO_REVISTA_2 ADD CONSTRAINT RefF_HGCG_REVISTA_29 
    FOREIGN KEY (REVISTA_ID)
    REFERENCES F_HGCG_REVISTA_2(REVISTA_ID)
;


-- 
-- TABLE: F_HGCG_SUSCRIPTOR_4 
--

ALTER TABLE F_HGCG_SUSCRIPTOR_4 ADD CONSTRAINT RefF_HGCG_PAIS_24 
    FOREIGN KEY (PAIS_ID)
    REFERENCES F_HGCG_PAIS_2(PAIS_ID)
;


