--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      s-03-autos-igcg-s1.DM1
-- Author :       Windows User
--
-- Date Created : Wednesday, February 03, 2021 20:04:45
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: CLIENTE_F2_IGCG_S1 
--

CREATE TABLE CLIENTE_F2_IGCG_S1(
    CLIENTE_ID            NUMBER(10, 0)    NOT NULL,
    NOMBRE                VARCHAR2(40)     NOT NULL,
    AP_PATERNO            VARCHAR2(40)     NOT NULL,
    AP_MATERNO            VARCHAR2(40)     NOT NULL,
    NUM_IDENTIFICACION    VARCHAR2(18)     NOT NULL,
    EMAIL                 VARCHAR2(500)    NOT NULL,
    CONSTRAINT CLIENTE_ID_PK PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_AUTO_F1_IGCG_S1 
--

CREATE TABLE HISTORICO_STATUS_AUTO_F1_IGCG_S1(
    HISTORICO_STATUS_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS           DATE             NOT NULL,
    AUTO_ID                NUMBER(10, 0)    NOT NULL,
    STATUS_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORICO_STATUS_ID_PK PRIMARY KEY (HISTORICO_STATUS_ID)
)
;



-- 
-- TABLE: MARCA_R_IGCG_S1 
--

CREATE TABLE MARCA_R_IGCG_S1(
    MARCA_ID       NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    CONSTRAINT MARCA_ID_PK PRIMARY KEY (MARCA_ID)
)
;



-- 
-- TABLE: MODELO_R_IGCG_S1 
--

CREATE TABLE MODELO_R_IGCG_S1(
    MODELO_ID      NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    MARCA_ID       NUMBER(10, 0)    NOT NULL,
    CONSTRAINT MODELO_ID_PK PRIMARY KEY (MODELO_ID)
)
;



-- 
-- TABLE: STATUS_AUTO_F1_IGCG_S1 
--

CREATE TABLE STATUS_AUTO_F1_IGCG_S1(
    STATUS_ID      NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(20)     NOT NULL,
    DESCRIPCION    VARCHAR2(40)     NOT NULL,
    CONSTRAINT STATUS_ID_PK PRIMARY KEY (STATUS_ID)
)
;



-- 
-- TABLE: SUCURSAL_F3_IGCG_S1 
--

CREATE TABLE SUCURSAL_F3_IGCG_S1(
    SUCURSAL_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    CLAVE                VARCHAR2(8)      NOT NULL,
    SUCURSAL_ANEXA_ID    NUMBER(38, 0),
    PAIS_ID              NUMBER(4, 0)     NOT NULL,
    CONSTRAINT SUCURSAL_ID_PK PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: TARJETA_CLIENTE_F2_IGCG_S1 
--

CREATE TABLE TARJETA_CLIENTE_F2_IGCG_S1(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NUM_TARJETA         VARCHAR2(16)     NOT NULL,
    CODIGO_SEGURIDAD    NUMBER(3, 0)     NOT NULL,
    CONSTRAINT TARJETA_CLIENTE_ID_PK PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_AUTO_F1_IGCG_S1 
--

ALTER TABLE HISTORICO_STATUS_AUTO_F1_IGCG_S1 ADD CONSTRAINT RefSTATUS_AUTO_F1_IGCG_S11 
    FOREIGN KEY (STATUS_ID)
    REFERENCES STATUS_AUTO_F1_IGCG_S1(STATUS_ID)
;


-- 
-- TABLE: MODELO_R_IGCG_S1 
--

ALTER TABLE MODELO_R_IGCG_S1 ADD CONSTRAINT RefMARCA_R_IGCG_S12 
    FOREIGN KEY (MARCA_ID)
    REFERENCES MARCA_R_IGCG_S1(MARCA_ID)
;


