--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      s-03-autos-igcg-s2.DM1
-- Author :       Windows User
--
-- Date Created : Wednesday, February 03, 2021 20:11:42
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: AUTO_F2_IGCG_S2 
--

CREATE TABLE AUTO_F2_IGCG_S2(
    AUTO_ID    NUMBER(10, 0)    NOT NULL,
    FOTO       BLOB             NOT NULL,
    CONSTRAINT AUTO_ID_PK PRIMARY KEY (AUTO_ID)
)
;



-- 
-- TABLE: CLIENTE_F2_IGCG_S2 
--

CREATE TABLE CLIENTE_F2_IGCG_S2(
    CLIENTE_ID            NUMBER(10, 0)    NOT NULL,
    NOMBRE                VARCHAR2(40)     NOT NULL,
    AP_PATERNO            VARCHAR2(40)     NOT NULL,
    AP_MATERNO            VARCHAR2(40)     NOT NULL,
    NUM_IDENTIFICACION    VARCHAR2(18)     NOT NULL,
    EMAIL                 VARCHAR2(500)    NOT NULL,
    CONSTRAINT CLIENTE_ID_PK PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_AUTO_F2_IGCG_S2 
--

CREATE TABLE HISTORICO_STATUS_AUTO_F2_IGCG_S2(
    HISTORICO_STATUS_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS           DATE             NOT NULL,
    STATUS_AUTO_ID         NUMBER(10, 0)    NOT NULL,
    AUTO_ID                NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORICO_STATUS_ID_PK PRIMARY KEY (HISTORICO_STATUS_ID)
)
;



-- 
-- TABLE: MARCA_R_IGCG_S2 
--

CREATE TABLE MARCA_R_IGCG_S2(
    MARCA_ID       NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    CONSTRAINT MARCA_ID_PK PRIMARY KEY (MARCA_ID)
)
;



-- 
-- TABLE: MODELO_R_IGCG_S2 
--

CREATE TABLE MODELO_R_IGCG_S2(
    MODELO_ID      NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    MARCA_ID       NUMBER(10, 0)    NOT NULL,
    CONSTRAINT MODELO_ID_PK PRIMARY KEY (MODELO_ID)
)
;



-- 
-- TABLE: STATUS_AUTO_F2_IGCG_A2 
--

CREATE TABLE STATUS_AUTO(
    STATUS_AUTO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE             VARCHAR2(20)     NOT NULL,
    DESCRIPCION       VARCHAR2(40)     NOT NULL,
    CONSTRAINT STATUS_AUTO_ID_PK PRIMARY KEY (STATUS_AUTO_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_AUTO_F2_IGCG_S2 
--

ALTER TABLE HISTORICO_STATUS_AUTO_F2_IGCG_S2 ADD CONSTRAINT RefSTATUS_AUTO_F2_IGCG_A21 
    FOREIGN KEY (STATUS_AUTO_ID)
    REFERENCES STATUS_AUTO(STATUS_AUTO_ID)
;

ALTER TABLE HISTORICO_STATUS_AUTO_F2_IGCG_S2 ADD CONSTRAINT RefAUTO_F2_IGCG_S22 
    FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO_F2_IGCG_S2(AUTO_ID)
;


-- 
-- TABLE: MODELO_R_IGCG_S2 
--

ALTER TABLE MODELO_R_IGCG_S2 ADD CONSTRAINT RefMARCA_R_IGCG_S23 
    FOREIGN KEY (MARCA_ID)
    REFERENCES MARCA_R_IGCG_S2(MARCA_ID)
;


