--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      s-03-autos-hgcg-s2.DM1
-- Author :       Windows User
--
-- Date Created : Wednesday, February 03, 2021 20:01:55
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: AUTO_CARGA_F2_HGCG_S2 
--

CREATE TABLE AUTO_CARGA_F2_HGCG_S2(
    AUTO_ID            NUMBER(10, 0)    NOT NULL,
    PESO_MAXIMO        NUMBER(10, 0)    NOT NULL,
    VOLUMEN            NUMBER(10, 0)    NOT NULL,
    TIPO_COMBUSTIBLE    CHAR(1)          NOT NULL,
    CONSTRAINT AUTO_ID_PK PRIMARY KEY (AUTO_ID)
)
;



-- 
-- TABLE: AUTO_F2_HGCG_S2 
--

CREATE TABLE AUTO_F2_HGCG_S2(
    AUTO_ID         NUMBER(10, 0)    NOT NULL,
    ANIO            NUMBER(4, 0)     NOT NULL,
    NUM_SERIE       VARCHAR2(20)     NOT NULL,
    TIPO            CHAR(1)          NOT NULL,
    PRECIO          NUMBER(9, 2)     NOT NULL,
    FECHA_STATUS    DATE             NOT NULL,
    MODELO_ID       NUMBER(10, 0)    NOT NULL,
    STATUS_AUTO_ID     NUMBER(10, 0)    NOT NULL,
    SUCURSAL_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT AUTO_ID_PK1 PRIMARY KEY (AUTO_ID)
)
;



-- 
-- TABLE: AUTO_PARTICULAR_F2_HGCG_S2 
--

CREATE TABLE AUTO_PARTICULAR_F2_HGCG_S2(
    AUTO_ID          NUMBER(10, 0)    NOT NULL,
    NUM_CILINDROS    NUMBER(1, 0)     NOT NULL,
    NUM_PASAJEROS    NUMBER(1, 0)     NOT NULL,
    CLASE            CHAR(1)          NOT NULL,
    CONSTRAINT AUTO_ID_PK10 PRIMARY KEY (AUTO_ID)
)
;



-- 
-- TABLE: CLIENTE_F1_HGCG_S2 
--

CREATE TABLE CLIENTE_F1_HGCG_S2(
    CLIENTE_ID            NUMBER(10, 0)    NOT NULL,
    NOMBRE                VARCHAR2(40)     NOT NULL,
    AP_PATERNO            VARCHAR2(40)     NOT NULL,
    AP_MATERNO            VARCHAR2(40)     NOT NULL,
    NUM_IDENTIFICACION    VARCHAR2(18)     NOT NULL,
    EMAIL                 VARCHAR2(500)    NOT NULL,
    CONSTRAINT CLIENTE_ID_PK1 PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: MARCA_R_HGCH_S2 
--

CREATE TABLE MARCA_R_HGCH_S2(
    MARCA_ID       NUMBER(3, 0)     NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    CONSTRAINT MARCA_ID_PK PRIMARY KEY (MARCA_ID)
)
;



-- 
-- TABLE: MODELO_R_HGCG_S2 
--

CREATE TABLE MODELO_R_HGCG_S2(
    MODELO_ID      NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    MARCA_ID       NUMBER(3, 0)     NOT NULL,
    CONSTRAINT MODELO_ID_PK PRIMARY KEY (MODELO_ID)
)
;



-- 
-- TABLE: PAGO_AUTO_F2_HGCG_S2 
--

CREATE TABLE PAGO_AUTO_F2_HGCG_S2(
    CLIENTE_ID     NUMBER(10, 0)    NOT NULL,
    AUTO_ID        NUMBER(10, 0)    NOT NULL,
    FECHA_PAGO     DATE             NOT NULL,
    IMPORTE        NUMBER(8, 2)     NOT NULL,
    RECIBO_PAGO    BLOB             NOT NULL,
    CONSTRAINT CLIENTE_AUTO_ID_PK PRIMARY KEY (CLIENTE_ID, AUTO_ID)
)
;



-- 
-- TABLE: PAIS_F2_HGCG_S2 
--

CREATE TABLE PAIS_F2_HGCG_S2(
    PAIS_ID    NUMBER(4, 0)    NOT NULL,
    CLAVE      VARCHAR2(4)     NOT NULL,
    NOMBRE     VARCHAR2(40)    NOT NULL,
    REGION     VARCHAR2(3)     NOT NULL,
    CONSTRAINT PAIS_ID_PK PRIMARY KEY (PAIS_ID)
)
;



-- 
-- TABLE: STATUS_AUTO_F2_HGCG_S2 
--

CREATE TABLE STATUS_AUTO(
    STATUS_AUTO_id    NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(20)     NOT NULL,
    DESCRIPCION    VARCHAR2(40)     NOT NULL,
    CONSTRAINT STATUS_AUTO_PK PRIMARY KEY (STATUS_AUTO_id)
)
;



-- 
-- TABLE: SUCURSAL_F2_HGCG_S2 
--

CREATE TABLE SUCURSAL_F2_HGCG_S2(
    SUCURSAL_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    CLAVE                VARCHAR2(8)      NOT NULL,
    SUCURSAL_ANEXA_ID    NUMBER(38, 0),
    PAIS_ID              NUMBER(4, 0)     NOT NULL,
    CONSTRAINT SUCURSAL_ID_PK PRIMARY KEY (SUCURSAL_ID)
)
;


-- 
-- TABLE: TARJETA_CLIENTE_F1_HGCG_S2 
--

CREATE TABLE TARJETA_CLIENTE_F1_HGCG_S2(
    CLIENTE_ID     NUMBER(10, 0)    NOT NULL,
    ANIO_EXPIRA    VARCHAR2(2)      NOT NULL,
    MES_EXPIRA     VARCHAR2(2)      NOT NULL,
    TIPO           CHAR(1)          NOT NULL,
    CONSTRAINT TARJETA_CLIENTE_ID_PK PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: AUTO_CARGA_F2_HGCG_S2 
--

ALTER TABLE AUTO_CARGA_F2_HGCG_S2 ADD CONSTRAINT RefAUTO_F2_HGCG_S26 
    FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO_F2_HGCG_S2(AUTO_ID)
;


-- 
-- TABLE: AUTO_F2_HGCG_S2 
--

ALTER TABLE AUTO_F2_HGCG_S2 ADD CONSTRAINT RefSUCURSAL_F2_HGCG_S28 
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F2_HGCG_S2(SUCURSAL_ID)
;

ALTER TABLE AUTO_F2_HGCG_S2 ADD CONSTRAINT RefMODELO_R_HGCG_S22 
    FOREIGN KEY (MODELO_ID)
    REFERENCES MODELO_R_HGCG_S2(MODELO_ID)
;

ALTER TABLE AUTO_F2_HGCG_S2 ADD CONSTRAINT RefSTATUS_AUTO_F2_HGCG_S23 
    FOREIGN KEY (STATUS_AUTO_ID)
    REFERENCES STATUS_AUTO(STATUS_AUTO_ID)
;


-- 
-- TABLE: AUTO_PARTICULAR_F2_HGCG_S2 
--

ALTER TABLE AUTO_PARTICULAR_F2_HGCG_S2 ADD CONSTRAINT RefAUTO_F2_HGCG_S27 
    FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO_F2_HGCG_S2(AUTO_ID)
;


-- 
-- TABLE: MODELO_R_HGCG_S2 
--

ALTER TABLE MODELO_R_HGCG_S2 ADD CONSTRAINT RefMARCA_R_HGCH_S24 
    FOREIGN KEY (MARCA_ID)
    REFERENCES MARCA_R_HGCH_S2(MARCA_ID)
;


-- 
-- TABLE: PAGO_AUTO_F2_HGCG_S2 
--

ALTER TABLE PAGO_AUTO_F2_HGCG_S2 ADD CONSTRAINT RefAUTO_F2_HGCG_S25 
    FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO_F2_HGCG_S2(AUTO_ID)
;


-- 
-- TABLE: SUCURSAL_F2_HGCG_S2 
--

ALTER TABLE SUCURSAL_F2_HGCG_S2 ADD CONSTRAINT RefPAIS_F2_HGCG_S21 
    FOREIGN KEY (PAIS_ID)
    REFERENCES PAIS_F2_HGCG_S2(PAIS_ID)
;


